name: Integration

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest #runs on a server, specify a name of server


    steps:
    - uses: actions/checkout@v3
    - run: docker build . -t boscotam/nest-app
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password stdin
    - run: docker push boscotam/nest-app